# Generated by Django 5.2 on 2025-04-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Наименование организации")),
                ("email", models.EmailField(max_length=50, verbose_name="Электронная почта")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("house_number", models.CharField(max_length=10, verbose_name="Номер дома")),
                (
                    "debt_to_supplier",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Остаток задолжности"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier_level",
                    models.CharField(
                        choices=[(0, "Factory"), (1, "Retail network"), (2, "Individual entrepreneur")],
                        max_length=1,
                        verbose_name="Уровень постащика",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_name",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "db_table": "suppliers",
            },
        ),
    ]
